//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupEase.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int taskId { get; set; }
        public int userId { get; set; }
        public System.Guid activityId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.DateTime dueDate { get; set; }
        public bool isComplete { get; set; }
        public System.DateTime createDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual User User { get; set; }
    }
}
